### ISSUE TITLE
dont find jest.config

### ISSUE THREAD

**Issue by brunokunace** [wallabyjs/wallaby-vue-compiler#2]
Hi, i dont know if is a correct repo for this issue.

I try to run wallaby on webstorm (2017) and vue-cli 3 (`@vue/cli`).
Copy all file wallaby config content on https://wallabyjs.com/docs/integration/vue.html

initial i have the problem (babel not find `@vue/app`) and after (dont find `@babel/core`) i installed both (`@vue/babel-preset-vue-app` and `@babel/core`)

now i have this error 

```
Error: Cannot find module './jest.conf'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at afterWrite (_stream_writable.js:454:3)
    at onwrite (_stream_writable.js:445:7)
    at InflateRaw.afterTransform (_stream_transform.js:90:3)
    at Zlib.callback (zlib.js:515:5)
```

i try to change this line of configuration
```
 const jestConfig = require('./package').jest || require('./jest.conf')
```

to ./test/unit/jest.config

but dont found.

i try to get jest.config.js and copy to root folder, but, same error.

Please check and send me to a correct repo if this is a wrong.

**Comment by ArtemGovorov** [comment]
Just did the following:
- installed the latest @vue/cli (v3.0.0-beta.11), 
- generated a project with `vue create my-project-l`, 
- added the [config from the docs](https://wallabyjs.com/docs/integration/vue.html#vuecli-v3x),
- ran `yarn add wallaby-vue-compiler -D` (as the docs say), 

and everything is working as expected:

<img width="826" alt="screen shot 2018-05-28 at 10 16 42 am" src="https://user-images.githubusercontent.com/979966/40592246-424236a2-6260-11e8-9db3-8f2735ecc3a9.png">

> i try to change this line of configuration
> const jestConfig = require('./package').jest || require('./jest.conf')

@vue/cli 3 docs don't have such line of code. We have the following line in our docs:
```js
const jestConfig = require('./package').jest || require('./jest.config')
```
because @vue/cli v3 generates `jest.config.js` file in the project's root (or config in `package.json` depending on your selection).

> i try to get jest.config.js and copy to root folder, but, same error.

Probably because your config has it under the `jest.conf` name and not the `jest.config` name.

> to ./test/unit/jest.config

@vue/cli v3 doesn't generate such file, but if you have moved your Jest config manually, then you'll need to add the `test/unit/jest.config.js` file to the `files` list of your wallaby config.

> initial i have the problem (babel not find `@vue/app`) and after (dont find `@babel/core`) i installed both (`@vue/babel-preset-vue-app` and `@babel/core`)

Looks like you are not running a project generated by `@vue/cli` then, because it should have all the modules that you have indicated as missing. Try checking that you are running the latest `@vue/cli`, and not `vue-cli v2.x`.
